### ISSUE TITLE
Multiple TM Notifications After One Send

### ISSUE THREAD

**Issue by p8gonzal** [UCSD/campus-mobile#1245]
Observed on iPhone 11 Pro Max, QA build 1263 - 7.6.0
Produced once at 10:56 and then at 10:58

![Photo Feb 17, 10 58 17 AM](https://user-images.githubusercontent.com/42155702/108394837-02d86280-71ca-11eb-9a11-eedfe623c7a2.png)

**Comment by c3bryant** [comment]
Notes:
  - `Test Campus Announcement [02-17-2021 \#2]` failed to send. Firebase returned 'Service unavailable' when attempting to send. 
  - Push status on messaging-center table is not updated with 'push failure' - line 151 messaging-center-trigger

messaging-center-trigger Logs:
```
2021-02-17T10:57 9e073f1a-8ee3-4e34-8a8a-2b8501ee5b66 INFO Error sending to topic campusAnnouncements
2021-02-17T10:57 9e073f1a-8ee3-4e34-8a8a-2b8501ee5b66 INFO Error: Error: The service is currently unavailable. at Runtime.exports.handler (/var/task/index.js:151:11) at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by c3bryant** [comment]
Unable to reproduce as of 04/01/21. Let's revisit if the problem surfaces again.
