### ISSUE TITLE
Unhandled Exception: needsLayout

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1420]
Time Tracking: MA-78

Exception encountered on `experimental` branch when switching tabs between Home and Profile.

This is done when:
- [ ] Switching tabs on experimental does not throw an exception

Steps to reproduce:
1. Clean build/install from `experimental`
2. Load Home view as a Visitor
3. Switch between Profile and Home tab several (5-10) times
4. Clicking Home or Profile tab eventually throws the error below
5. Upon error thrown, the user will not be navigated to the tab they pressed. Clicking the same tab again navigates the user to that tab in most cases
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/painting/text_painter.dart': Failed assertion: line 881 pos 12: '!_needsLayout': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      TextPainter.getPositionForOffset (package:flutter/src/painting/text_painter.dart:881:12)
#3      RenderParagraph.hitTestChildren (package:flutter/src/rendering/paragraph.dart:456:52)
#4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#5      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#6      RenderTransform.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2347:22)
#7      BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:826:31)
#8      BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:751:12)
#9      RenderTransform.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2343:19)
#10     RenderTransform.hitTest (package:flutter/src/rendering/proxy_box.dart:2337:12)
#11     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#12     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#13     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:92:25)
#14     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
#15     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:87:21)
#16     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#17     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2775:25)
#18     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
#19     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2770:33)
#20     RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:1072:12)
#21     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#22     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:92:25)
#23     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
#24     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:87:21)
#25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#26     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#27     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178:19)
#28     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#30     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#31     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#32     RenderMouseRegion.hitTest (package:flutter/src/rendering/proxy_box.dart:2905:18)
#33     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#35     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#36     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#37     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#38     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178:19)
#39     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2775:25)
#40     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
#41     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2770:33)
#42     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:620:12)
#43     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#44     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#45     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#46     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2775:25)
#47     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
#48     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2770:33)
#49     RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:1072:12)
#50     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#51     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:92:25)
#52     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
#53     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:87:21)
#54     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#55     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#56     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#57     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#58     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:535:18)
#59     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#60     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#61     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:535:18)
#62     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#63     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#64     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#65     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#66     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#67     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#68     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#69     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1889:18)
#70     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#71     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#72     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2775:25)
#73     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
#74     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2770:33)
#75     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:414:12)
#76     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#77     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#78     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#79     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#80     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#81     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1889:18)
#82     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#83     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#84     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#85     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#86     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#87     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#88     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3257:31)
#89     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2775:25)
#90     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
#91     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2770:33)
#92     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:620:12)
#93     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#94     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#95     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#96     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#97     RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2714:22)
#98     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
#99     RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2708:19)
#100    RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2694:12)
#101    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#102    RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2714:22)
#103    BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
#104    RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2708:19)
#105    RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2694:12)
#106    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#107    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#108    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#109    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#110    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#111    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#112    RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3376:31)
#113    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#114    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#115    _RenderTheatre.hitTestChildren.<anonymous closure> (package:flutter/src/widgets/overlay.dart:765:25)
#116    BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
#117    _RenderTheatre.hitTestChildren (package:flutter/src/widgets/overlay.dart:760:33)
#118    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#119    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#120    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#121    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#122    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#123    RenderAbsorbPointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3474:17)
#124    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#125    RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178:19)
#126    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#127    RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:535:18)
#128    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#129    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#130    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#131    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#132    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#133    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
#134    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
#135    RenderView.hitTest (package:flutter/src/rendering/view.dart:173:14)
#136    RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:490:16)
#137    GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:346:7)
#138    GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#139    GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#140    GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#141    _rootRunUnary (dart:async/zone.dart:1370:13)
#142    _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#143    _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#144    _invoke1 (dart:ui/hooks.dart:182:10)
#145    PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
#146    _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
```

**Comment by keskinmbaha** [comment]
Following this thread https://github.com/flutter/flutter/issues/86545 and testing it myself, I found out the exception seems to be thrown if the user taps on the hidden label below any tab in the BottomNavigationBar.

**Comment by keskinmbaha** [comment]
I found out the exception is thrown if the user taps on the hidden label below any tab in the BottomNavigationBar.

**Comment by keskinmbaha** [comment]
https://github.com/flutter/flutter/issues/86545. Issue is caused by user tapping on hidden label below the tab icons.

**Comment by keskinmbaha** [comment]
A temporary solution would be to show both the selected and unselected labels instead of setting them to false.
